# action.yml
name: 'Load available actions'
author: 'Rob Bos'
description: 'Load an overview of all available actions in a GitHub Organization by looking for the action.yml/yaml files.'
branding:
  icon : alert-circle
  color: blue
inputs:
  organization:
    description: 'Slug of the organization to analyze. Either this or the user slug needs to have a value'
    required: false
  user:
    description: 'Slug of the user space to analyze. Either this or the organization slug needs to have a value'
    required: false
  PAT:
    description: 'Personal access token to use for analysis. Leaving this empty will use the default GITHUB_TOKEN that could have limited access rights'
    required: true 
  removeToken: 
    description: 'Remove hardcoded token before returning'
    required: false
  fetchReadmes:
    description: 'Fetch readmes of actions'
    required: false
  outputFilename:
    description: 'Define the name of the output file'
    required: false
outputs:
  actions-file-path:
    description: 'Path to the file that contains a list of all actions available in the organization or user space'  
runs:
  using: 'node16'
  main: 'dist/main.js'
